version: "3.8"

x-app: &default-app
    restart: always
    build:
        context: ../..
        target: production
    depends_on:
        - postgres
        - rabbit
        - redis
    volumes:
        - /mnt:/mnt
        - adit_data:/var/www/adit
    env_file:
        - ../../.env
    environment:
        USE_DOCKER: 1
        DJANGO_SETTINGS_MODULE: "adit.settings.production"
        DATABASE_URL: "psql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres"
        RABBITMQ_URL: "amqp://rabbit"
        REDIS_URL: "redis://redis:6379/0"
        DJANGO_STATIC_ROOT: "/var/www/adit/static/"
        SSL_CERT_FILE: "/var/www/adit/ssl/cert.pem"
        SSL_KEY_FILE: "/var/www/adit/ssl/key.pem"
        FLOWER_HOST: "flower"
        FLOWER_PORT: "5555"
        SYSLOG_HOST: "syslog"
        SYSLOG_PORT: "514"

services:
    web:
        <<: *default-app
        ports:
            - "80:80"
            - "443:443"
        command: >
            bash -c "
              ./scripts/wait-for-it.sh postgres:5432 -t 30 &&
              python ./manage.py migrate &&
              python ./manage.py collectstatic --no-input &&
              python ./manage.py create_admin &&
              python ./manage.py generate_cert &&
              daphne -b 0.0.0.0 -p 80 -e ssl:443:privateKey=/var/www/adit/ssl/key.pem:certKey=/var/www/adit/ssl/cert.pem adit.asgi:application
            "

    worker_default:
        <<: *default-app
        command: python manage.py celery_worker -Q default_queue

    worker_dicom_task:
        <<: *default-app
        command: python manage.py celery_worker -Q dicom_task_queue

    celery_beat:
        <<: *default-app
        command: python manage.py celery_beat

    receiver:
        <<: *default-app
        ports:
            - "11112:11112"
        command: python manage.py receiver

    flower:
        <<: *default-app
        expose:
            - "5555"
        command: celery flower -A adit --url_prefix=flower

    postgres:
        restart: always
        image: postgres:13.1
        expose:
            - "5432"
            - "15672"
        env_file:
            - .env
        volumes:
            - postgres_data:/var/lib/postgresql/data

    rabbit:
        restart: always
        image: rabbitmq:3.8-management
        expose:
            - "5672"
        volumes:
            - rabbit_data:/var/lib/rabbitmq

    redis:
        restart: always
        image: redis:6.0
        expose:
            - "6379"
        volumes:
            - redis_data:/data

    syslog:
        image: balabit/syslog-ng:3.30.1

volumes:
    adit_data: # For statics, SSL certs, logs, Celery Beat db
    postgres_data:
    rabbit_data:
    redis_data:
    flower_data:
