version: "3.8"

x-app:
    &default-app
    restart: always
    build:
        context: ../..
        target: production
    image: adit_prod:latest
    depends_on:
        - syslog
        - postgres
        - rabbit
        - redis
        - orthanc1
        - orthanc2
    volumes:
        - /mnt:/mnt
    env_file:
        - ./.env
    environment:
        USE_DOCKER: 1
        ADIT_FULLSTACK: 1
        DJANGO_SETTINGS_MODULE: "adit.settings.production"
        DATABASE_URL: "psql://postgres:postgres@postgres:5432/postgres"
        RABBITMQ_URL: "amqp://rabbit"
        REDIS_URL: "redis://redis:6379/0"
        DJANGO_STATIC_ROOT: "/var/www/adit/static/"
        SSL_CERT_FILE: "/var/www/adit/ssl/cert.pem"
        SSL_KEY_FILE: "/var/www/adit/ssl/key.pem"
        RABBIT_MANAGEMENT_HOST: "rabbit"
        RABBIT_MANAGEMENT_PORT: "15672"
        FLOWER_HOST: "flower"
        FLOWER_PORT: "5555"
        SYSLOG_HOST: "syslog"
        SYSLOG_PORT: "514"
        ORTHANC1_HOST: "orthanc1"
        ORTHANC1_HTTP_PORT: 6501
        ORTHANC1_DICOM_PORT: 7501
        ORTHANC2_HOST: "orthanc2"
        ORTHANC2_HTTP_PORT: 6502
        ORTHANC2_DICOM_PORT: 7502

services:
    web:
        <<: *default-app
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /mnt:/mnt
            - adit_data:/var/www/adit
        command: >
            bash -c "
              ./scripts/wait-for-it.sh postgres:5432 -t 30 &&
              python ./manage.py migrate &&
              python ./manage.py collectstatic --no-input &&
              python ./manage.py create_admin &&
              python ./manage.py generate_cert &&
              daphne -b 0.0.0.0 -p 80 -e ssl:443:privateKey=/var/www/adit/ssl/key.pem:certKey=/var/www/adit/ssl/cert.pem adit.asgi:application
            "

    worker_default:
        <<: *default-app
        command: python manage.py celery_worker -Q default_queue

    worker_dicom_task:
        <<: *default-app
        command: python manage.py celery_worker -Q dicom_task_queue

    celery_beat:
        <<: *default-app
        command: python manage.py celery_beat

    receiver:
        <<: *default-app
        ports:
            - "11112:11112"
        command: python manage.py receiver

    flower:
        <<: *default-app
        expose:
            - "5555"
        command: celery --broker=amqp://rabbit/ flower --url_prefix=flower

    postgres:
        restart: always
        image: postgres:13.1
        expose:
            - "5432"
        env_file:
            - ./.env
        volumes:
            - postgres_data:/var/lib/postgresql/data

    # RabbitMQ authentication can't be disabled. So when we try to log into
    # the management console we have to use "guest" as username and password.
    # The real authentication happens by ADIT itself, because the management
    # console is behind a ProxyView.
    rabbit:
        restart: always
        image: rabbitmq:3.8-management
        expose:
            - "5672"
            - "15672"
        volumes:
            - rabbit_data:/var/lib/rabbitmq

    redis:
        restart: always
        image: redis:6.0
        expose:
            - "6379"
        volumes:
            - redis_data:/data

    syslog:
        image: balabit/syslog-ng:3.30.1
        expose:
            - "514"
        volumes:
            - ../syslog/logrotate.conf:/etc/logrotate.conf
            - ../syslog/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
            - syslog_data:/var/log

    orthanc1:
        image: jodogne/orthanc-plugins:1.8.1
        expose:
            - "6501"
            - "7501"
        volumes:
            - ../orthanc1/orthanc.json:/etc/orthanc/orthanc.json
            - orthanc1_data:/var/lib/orthanc/db

    orthanc2:
        image: jodogne/orthanc-plugins:1.8.1
        expose:
            - "6502"
            - "7502"
        volumes:
            - ../orthanc2/orthanc.json:/etc/orthanc/orthanc.json
            - orthanc2_data:/var/lib/orthanc/db

volumes:
    adit_data:
    postgres_data:
    rabbit_data:
    redis_data:
    flower_data:
    syslog_data:
    orthanc1_data:
    orthanc2_data:
