version: "3.8"

x-app: &default-app
    build:
        context: ../..
        target: development
    depends_on:
        - postgres
        - rabbit
        - redis
        - orthanc_1
        - orthanc_2
    volumes:
        - ../..:/app
        - /mnt:/mnt
        - adit_data:/var/www/adit
        - vscode-server:/root/.vscode-server/extensions
        - vscode-server-insiders:/root/.vscode-server-insiders/extensions
    environment:
        ENABLE_REMOTE_DEBUGGING: 0
        USE_DOCKER: 1
        DJANGO_SETTINGS_MODULE: "adit.settings.development"
        DATABASE_URL: "psql://postgres:postgres@postgres:5432/postgres"
        RABBITMQ_URL: "amqp://rabbit"
        REDIS_URL: "redis://redis:6379/0"
        DJANGO_STATIC_ROOT: "/var/www/adit/static/"
        LOG_FOLDER: "/var/www/adit/logs"
        FLOWER_HOST: "flower"
        FLOWER_PORT: "5555"
        ORTHANC1_HOST: "orthanc_1"
        ORTHANC2_HOST: "orthanc_2"

services:
    web:
        <<: *default-app
        ports:
            - "8000:8000"
            - "5678:5678"
        command: >
            bash -c "
              ./scripts/wait-for-it.sh postgres:5432 -t 30 &&
              python ./manage.py reset_orthancs &&
              python ./manage.py migrate &&
              python ./manage.py collectstatic --no-input &&
              python ./manage.py populate_dev_db &&
              python ./manage.py runserver 0.0.0.0:8000
            "

    worker_default:
        <<: *default-app
        command: python manage.py celery_worker -Q default --autoreload

    worker_transfer:
        <<: *default-app
        command: python manage.py celery_worker -Q transfer --autoreload

    celery_beat:
        <<: *default-app
        command: python manage.py celery_beat --autoreload

    receiver:
        <<: *default-app
        expose:
            - "11112"
        command: python manage.py receiver --autoreload

    flower:
        <<: *default-app
        expose:
            - "5555"
        command: celery flower -A adit --url_prefix=flower

    postgres:
        image: postgres:latest
        expose:
            - "5432"
        environment:
            POSTGRES_PASSWORD: "postgres"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    rabbit:
        image: rabbitmq:latest
        expose:
            - "5672"
        volumes:
            - rabbit_data:/var/lib/rabbitmq

    redis:
        image: redis:latest
        expose:
            - "6379"
        volumes:
            - redis_data:/data

    orthanc_1:
        image: jodogne/orthanc-plugins:latest
        ports:
            - "6501:6501"
            - "7501:7501"
        volumes:
            - ../orthanc1_config.json:/etc/orthanc/orthanc.json
            - orthanc1_data:/var/lib/orthanc/db

    orthanc_2:
        image: jodogne/orthanc-plugins:latest
        ports:
            - "6502:6502"
            - "7502:7502"
        volumes:
            - ../orthanc2_config.json:/etc/orthanc/orthanc.json
            - orthanc2_data:/var/lib/orthanc/db

volumes:
    adit_data: # For statics, logs, Celery Beat db
    vscode-server:
    vscode-server-insiders:
    postgres_data:
    rabbit_data:
    redis_data:
    flower_data:
    orthanc1_data:
    orthanc2_data:
