image:
  file: .gitpod.Dockerfile

tasks:
  # A terminal where all services are started
  # supervisor is already installed in .gitpod.Dockerfile
  - before: supervisord -c ./gitpod/supervisord.conf
    init: |
      mkdir /workspace/adit/staticfiles
      touch /tmp/.pip-install-lock
      pipenv install --dev
      rm /tmp/.pip-install-lock
      createdb adit
      pipenv run python manage.py migrate
      pipenv run python manage.py populate_dev_db
      pipenv run python manage.py reset_orthancs
    command: |
      supervisorctl start celery:
      pipenv run python manage.py runserver

  # A terminal for continous testing
  - init: sleep 1 && while [ -f /tmp/.pip-install-lock ]; do sleep 1; done
    command: |
      # Alternatives for continous testing:
      # with pytest-picked: ptw --runner 'pytest --picked'
      # with pytest-testmon: ptw --runner 'pytest -s --testmon' (sometimes cumbersome and .testmondb must be deleted)
      # with pytest-xdist: pytest --looponfail (doesn't work with Orthanc db in the working dir)
      pipenv run pytest --cov=. # run all test once (with coverage report)
      pipenv run ptw --runner 'pytest --picked'

  # A terminal for the developer to do stuff
  - init: sleep 1 && while [ -f /tmp/.pip-install-lock ]; do sleep 1; done
    command: echo 'For your convenience!' && pipenv shell

ports:
  - port: 5432 # PostgreSQL
    onOpen: ignore
  - port: 5555 # Flower (for Celery)
    onOpen: ignore
  - port: 6379 # Redis Server
    onOpen: ignore
  - port: 6501 # Orhtanc 1 DICOM Server
    onOpen: ignore
  - port: 6502 # Orhtanc 2 DICOM Server
    onOpen: ignore
  - port: 7501 # Orhtanc 1 Webserver
    onOpen: ignore
  - port: 7502 # Orhtanc 2 Webserver
    onOpen: ignore
  - port: 8000 # Django Dev Webserver
    onOpen: notify
  - port: 9001 # Supervisord Webserver
    onOpen: ignore

vscode:
  extensions:
    - batisteo.vscode-django@0.20.0:gUr2ptf5xx2Pcb6pNcYqgw==
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
    - esbenp.prettier-vscode@5.1.3:t532ajsImUSrA9N8Bd7jQw==
