image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install -r /workspace/adit/requirements.txt
      createdb adit_dev
      python manage.py migrate
    command: python manage.py runserver

ports:
  - port: 5432 # PostgreSQL
    onOpen: ignore

vscode:
  extensions:
    - batisteo.vscode-django@0.20.0:gUr2ptf5xx2Pcb6pNcYqgw==
    - GrapeCity.gc-excelviewer@2.1.35:7NzkeRn7IqFadY0v3fCHwQ==