image:
  file: .gitpod.Dockerfile

tasks:
  - before: supervisord # supervisor is already installed in .gitpod.Dockerfile
    init: |
      sleep 1
      touch /tmp/.pip-install-lock
      pip install -r /workspace/adit/requirements.txt
      rm /tmp/.pip-install-lock
      createdb adit_dev
      python manage.py migrate
      python manage.py populate_dev_db
      python manage.py reset_orthancs
    command: python manage.py runserver

  - init: sleep 1 && while [ -f /tmp/.pip-install-lock ]; do sleep 1; done
    command: ptw --runner 'pytest -s --testmon'

  - command: echo 'For your convenience!'

ports:
  - port: 5432 # PostgreSQL
    onOpen: ignore
  - port: 6379 # Redis Server
    onOpen: ignore
  - port: 6501 # Orhtanc 1 DICOM Server
    onOpen: ignore
  - port: 6502 # Orhtanc 2 DICOM Server
    onOpen: ignore
  - port: 7501 # Orhtanc 1 Webserver
    onOpen: ignore
  - port: 7502 # Orhtanc 2 Webserver
    onOpen: ignore
  - port: 8000 # Django Dev Webserver
    onOpen: notify
  - port: 9001 # Supervisord Webserver
    onOpen: ignore
    
vscode:
  extensions:
    - batisteo.vscode-django@0.20.0:gUr2ptf5xx2Pcb6pNcYqgw==