image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install -r /workspace/adit/requirements.txt
      createdb adit
      python manage.py migrate
    command: python manage.py runserver

ports:
  - port: 5432
    onOpen: ignore
