image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install -r /workspace/adit/requirements.txt
      createdb adit_dev
      python manage.py migrate
    command: python manage.py runserver

  - command: ptw

  - command: redis-server

  - command: Orthanc /workspace/adit/_debug/orthanc_config1.json

  - command: Orthanc /workspace/adit/_debug/orthanc_config2.json

ports:
  - port: 5432 # PostgreSQL
    onOpen: ignore
  - port: 6379 # Redis Server
    onOpen: ignore
  - port: 3501 # Orhtanc 1 (DICOM port)
    onOpen: ignore
  - port: 3502 # Orhtanc 2 (DICOM port)
    onOpen: ignore

vscode:
  extensions:
    - batisteo.vscode-django@0.20.0:gUr2ptf5xx2Pcb6pNcYqgw==
    - GrapeCity.gc-excelviewer@2.1.35:7NzkeRn7IqFadY0v3fCHwQ==