image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      cd /workspace/adit/webserver/
      pip install -r ./requirements.txt
      createdb adit
      python manage.py migrate
    command: python manage.py runserver

ports:
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - batisteo.vscode-django@0.20.0:gUr2ptf5xx2Pcb6pNcYqgw==