version: "3.8"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres" # TODO: move to .env file
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/src
    environment:
      DATABASE_URL: "psql://postgres:postgres@postgres:5432/postgres"
      DJANGO_SETTINGS_MODULE: "adit.settings.development"
      USE_DOCKER: 1
      ORTHANC1_HOST: "orthanc_1"
      ORTHANC2_HOST: "orthanc_2"
    command: >
      bash -c "
        python ./manage.py migrate &&
        python manage.py populate_dev_db &&
        python ./manage.py runserver 0.0.0.0:8000
      "

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker_low_1:
    build: .
    volumes:
      - .:/src
    depends_on:
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: "adit.settings.development"
      REDIS_URL: "redis://redis:6379/0"
    command: celery -A adit worker -Q low -l info -n celery_worker_low_1

  celery_worker_high_1:
    build: .
    volumes:
      - .:/src
    depends_on:
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: "adit.settings.development"
      REDIS_URL: "redis://redis:6379/0"
    command: celery -A adit worker -Q low -l info -n celery_worker_high_1

  orthanc_1:
    image: jodogne/orthanc-plugins:latest
    ports:
      - "6501:6501"
      - "7501:7501"
    volumes:
      - ./compose/orthanc1_config.json:/etc/orthanc/orthanc.json

  orthanc_2:
    image: jodogne/orthanc-plugins:latest
    ports:
      - "6502:6502"
      - "7502:7502"
    volumes:
      - ./compose/orthanc2_config.json:/etc/orthanc/orthanc.json

volumes:
  postgres_data:
  redis_data:
