version: "3.8"

x-app: &default-app
  restart: always
  build:
    context: .
    target: production
  depends_on:
    - postgres
    - redis
  volumes:
    - /mnt:/mnt
    - web_data:/var/www/adit
  env_file:
    - .env
  environment:
    USE_DOCKER: 1
    DJANGO_SETTINGS_MODULE: "adit.settings.production"
    DATABASE_URL: "psql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres"
    REDIS_URL: "redis://redis:6379/0"
    DJANGO_STATIC_ROOT: "/var/www/adit/static/"
    SSL_CERT_FILE: "/var/www/adit/ssl/cert.pem"
    SSL_KEY_FILE: "/var/www/adit/ssl/key.pem"
    FLOWER_HOST: "flower"
    FLOWER_PORT: "5555"

services:
  web:
    <<: *default-app
    ports:
      - "80:80"
      - "443:443"
    command: >
      bash -c "
        ./scripts/wait-for-it.sh postgres:5432 -t 30 &&
        python ./manage.py migrate &&
        python ./manage.py collectstatic --no-input &&
        python ./manage.py create_admin &&
        python ./manage.py generate_cert &&
        daphne -b 0.0.0.0 -p 80 -e ssl:443:privateKey=/var/www/adit/ssl/key.pem:certKey=/var/www/adit/ssl/cert.pem adit.asgi:application
      "

  worker_default:
    <<: *default-app
    command: bash -c "celery -A adit worker -Q default -l warning -n worker_default_$$(hostname)"

  worker_low:
    <<: *default-app
    command: bash -c "celery -A adit worker -Q low -l warning -n worker_low_$$(hostname)"

  postgres:
    restart: always
    image: postgres:latest
    expose:
      - "5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - redis_data:/data

  flower:
    restart: always
    image: mher/flower
    expose:
      - "5555"
    depends_on:
      - redis
    volumes:
      - flower_data:/data
    command: flower --url_prefix=flower --broker=redis://redis:6379/0

volumes:
  web_data: # in production for static files, SSL certs and logs
  postgres_data:
  redis_data:
  flower_data:
