version: "3.8"

services:
  # TODO add secret_key, ADMIN_NAME, ADMIN_EMAIL to .env file
  postgres:
    restart: always
    image: postgres:latest
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "postgres" # TODO secure pass and move to .env file
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    restart: always
    build: .
    ports:
      - "80:8000" # TODO https and ws port? daphne?
    depends_on:
      - postgres
    volumes:
      - .:/src
    environment:
      DATABASE_URL: "psql://postgres:postgres@postgres:5432/postgres"
      DJANGO_SETTINGS_MODULE: "adit.settings.production"
      USE_DOCKER: 1
      FLOWER_HOST: "flower"
      FLOWER_PORT: "5555"
    command: > # TODO completely other command
      bash -c "
        python ./manage.py migrate &&
        python manage.py populate_dev_db &&
        python ./manage.py runserver 0.0.0.0:8000
      "

  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - redis_data:/data

  celery_worker_low:
    restart: always
    build: .
    volumes:
      - .:/src
    depends_on:
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: "adit.settings.production"
      REDIS_URL: "redis://redis:6379/0"
    command: bash -c "celery -A adit worker -Q low -l info -n celery_worker_low_$$(hostname)"

  celery_worker_high:
    restart: always
    build: .
    volumes:
      - .:/src
    depends_on:
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: "adit.settings.production"
      REDIS_URL: "redis://redis:6379/0"
    command: bash -c "celery -A adit worker -Q low -l info -n celery_worker_high_$$(hostname)"

  flower:
    restart: always
    image: mher/flower
    expose:
      - "5555"
    command: flower --url_prefix=flower --broker=redis://redis:6379/0

volumes:
  postgres_data:
  redis_data:
