version: "3.8"

services:
  postgres:
    restart: always
    image: postgres:latest
    expose:
      - "5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    restart: always
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - "80:8000" # TODO https and ws port? daphne?
    depends_on:
      - postgres
    volumes:
      - .:/src
    environment:
      DATABASE_URL: "psql://postgres:postgres@postgres:5432/postgres"
      DJANGO_SETTINGS_MODULE: "adit.settings.production"
      USE_DOCKER: 1
      FLOWER_HOST: "flower"
      FLOWER_PORT: "5555"
    env_file:
      - .env
    command: >
      bash -c "
        python ./manage.py migrate &&
        python ./manage.py collectstatic &&
        python ./manage.py create_admin &&
        daphne -b 0.0.0.0 -p 8000 adit.asgi:application
      "

  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - redis_data:/data

  celery_worker_low:
    restart: always
    build:
      context: .
      dockerfile: prod.Dockerfile
    volumes:
      - .:/src
    depends_on:
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: "adit.settings.production"
      REDIS_URL: "redis://redis:6379/0"
    env_file:
      - .env
    command: bash -c "celery -A adit worker -Q low -l info -n celery_worker_low_$$(hostname)"

  celery_worker_high:
    restart: always
    build:
      context: .
      dockerfile: prod.Dockerfile
    volumes:
      - .:/src
    depends_on:
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: "adit.settings.production"
      REDIS_URL: "redis://redis:6379/0"
    env_file:
      - .env
    command: bash -c "celery -A adit worker -Q low -l info -n celery_worker_high_$$(hostname)"

  flower:
    restart: always
    image: mher/flower
    expose:
      - "5555"
    command: flower --url_prefix=flower --broker=redis://redis:6379/0

volumes:
  postgres_data:
  redis_data:
