[tool.poetry]
name = "adit"
version = "0.17.0"
description = ""
authors = ["medihack <kai.schlamp@gmail.com>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.8"
psycopg2 = "^2.8.6"
channels = "^3.0.4"
whitenoise = "^5.2.0"
django-registration-redux = "^2.8"
django-crispy-forms = "^1.14.0"
django-tables2 = "^2.3.3"
django-environ = "^0.4.5"
djangorestframework = "^3.13.1"
Markdown = "^3.3.3"
django-filter = "^2.4.0"
pydicom = "^2.1.1"
pynetdicom = "^1.5.3"
cchardet = "^2.1.7"
redis = "^3.5.3"
celery = "^4.4.7"
flower = "^0.9.5"
django-revproxy = "^0.10.0"
django-loginas = "^0.3.9"
cryptography = "^3.2.1"
Twisted = {extras = ["tls", "http2"], version = "^20.3.0"}
dicognito = "^0.12.0"
pika = "^1.1.0"
django-extensions = "^3.1.5"
humanize = "^4.0.0"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-django = "^4.5.2"
pytest-cov = "^3.0.0"
pytest-watch = "^4.2.0"
pytest-picked = "^0.4.4"
coverage = "^5.3"
pylint = "^2.12.2"
pylint-django = "^2.5.1"
pylint-celery = "^0.3"
pylint-pytest = "^1.1.2"
black = "^22.1.0"
factory-boy = "^3.1.0"
Faker = "^4.14.2"
time-machine = "^2.1.0"
django-debug-toolbar = "^3.2.4"
django-debug-permissions = "^1.0.0"
requests = "^2.24.0"
ipython = "^8.0.1"
debugpy = "^1.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
