[tool.poetry]
name = "adit"
version = "0.23.3"
description = "ADIT (Automated DICOM Transfer) is a swiss army knife to exchange DICOM data between various systems by using a convenient web frontend."
authors = ["medihack <kai.schlamp@gmail.com>"]
license = "GPLv3"

[tool.poetry.dependencies]
cchardet = "^2.1.7"
celery = "^5.2.7"
channels = "^4.0.0"
cryptography = "^39.0.2"
dicognito = "^0.15.0"
Django = "^4.0.6"
django-crispy-forms = "^2.0"
django-environ = "^0.10.0"
django-extensions = "^3.1.5"
django-filter = "^22.1"
django-loginas = "^0.3.9"
django-registration-redux = "^2.10"
django-revproxy = {git = "https://github.com/jazzband/django-revproxy.git"}
django-tables2 = "^2.3.3"
djangorestframework = "^3.13.1"
flower = "^1.0.0"
humanize = "^4.0.0"
Markdown = "^3.3.7"
pika = "^1.1.0"
psycopg2 = "^2.9.3"
pydicom = "^2.3.0"
pynetdicom = "^2.0.2"
python = "^3.9"
redis = "^4.3.4"
toml = "^0.10.2"
Twisted = {extras = ["tls", "http2"], version = "^22.2.0"}
whitenoise = "^6.0.0"
daphne = "^4.0.0"
channels-redis = "^4.0.0"
crispy-bootstrap4 = "^2022.1"
django-htmx = "^1.14.0"

[tool.poetry.dev-dependencies]
black = "^23.1.0"
debugpy = "^1.6.2"
django-debug-permissions = "^1.0.0"
django-debug-toolbar = "^3.2.4"
factory-boy = "^3.1.0"
Faker = "^17.6.0"
ipython = "^8.1.1"
pytest = "^7.1.2"
pytest-cov = "^4.0.0"
pytest-django = "^4.5.2"
pytest-picked = "^0.4.4"
pytest-watch = "^4.2.0"
requests = "^2.27.1"
time-machine = "^2.1.0"
pyright = "^1.1.264"
django-types = "^0.17.0"
celery-types = "^0.14.0"
pytest-playwright = "^0.3.0"
pytest-celery = "^0.0.0"
ipykernel = "^6.17.1"
ruff = "^0.0.255"

[tool.ruff]
exclude = ["migrations"]
line-length = 100
select = ["E", "F", "I", "DJ"]

[tool.black]
exclude = "migrations"
line-length = 100

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
