[tool.poetry]
name = "adit"
version = "0.22.0"
description = ""
authors = ["medihack <kai.schlamp@gmail.com>"]
license = "GPLv3"

[tool.poetry.dependencies]
cchardet = "^2.1.7"
celery = "^5.2.7"
channels = "^3.0.5"
cryptography = "^38.0.2"
dicognito = "^0.15.0"
Django = "^4.0.6"
django-crispy-forms = "^1.14.0"
django-environ = "^0.9.0"
django-extensions = "^3.1.5"
django-filter = "^22.1"
django-loginas = "^0.3.9"
django-registration-redux = "^2.10"
django-revproxy = {git = "https://github.com/jazzband/django-revproxy.git"}
django-tables2 = "^2.3.3"
djangorestframework = "^3.13.1"
flower = "^1.0.0"
humanize = "^4.0.0"
Markdown = "^3.3.7"
pika = "^1.1.0"
psycopg2 = "^2.9.3"
pydicom = "2.3.0"
pynetdicom = "^2.0.2"
python = "^3.9"
redis = "4.3.4"
toml = "^0.10.2"
Twisted = {extras = ["tls", "http2"], version = "^22.2.0"}
whitenoise = "^6.0.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
debugpy = "^1.6.2"
django-debug-permissions = "^1.0.0"
django-debug-toolbar = "^3.2.4"
factory-boy = "^3.1.0"
Faker = "^15.1.1"
ipython = "^8.1.1"
pylint = "^2.12.2"
pylint-celery = "^0.3"
pylint-django = "^2.5.2"
pylint-pytest = "^1.1.2"
pytest = "^7.1.2"
pytest-cov = "^4.0.0"
pytest-django = "^4.5.2"
pytest-picked = "^0.4.4"
pytest-watch = "^4.2.0"
requests = "^2.27.1"
time-machine = "^2.1.0"
pyright = "^1.1.264"
django-types = "^0.16.0"
celery-types = "^0.14.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
