version: "3.8"

x-app:
  &default-app
  image: adit_dev:latest
  volumes:
    - ..:/app
  env_file:
    - ./.env.dev
  environment:
    ENABLE_REMOTE_DEBUGGING: 0
    DJANGO_SETTINGS_MODULE: "adit.settings.development"

services:
  web:
    <<: *default-app
    build:
      target: development
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      # Cave, overwrites the above anchor
      - ..:/app
      - vscode-server:/root/.vscode-server/extensions
      - vscode-server-insiders:/root/.vscode-server-insiders/extensions
    command: >
      bash -c "
        wait-for-it -s postgres:5432 -t 60 && 
        ./manage.py reset_orthancs &&
        ./manage.py migrate &&
        ./manage.py collectstatic --no-input &&
        ./manage.py populate_dev_db &&
        ./manage.py runserver 0.0.0.0:8000
      "

  worker_default:
    <<: *default-app
    command: |
      ./manage.py celery_worker -Q default_queue --autoreload

  worker_dicom_task:
    <<: *default-app
    command: |
      ./manage.py celery_worker -Q dicom_task_queue --autoreload

  celery_beat:
    <<: *default-app
    command: |
      ./manage.py celery_beat --autoreload

  receiver:
    <<: *default-app
    ports:
      - "11122:11112"
    command: |
      ./manage.py receiver --autoreload

  flower:
    <<: *default-app

  postgres:
    environment:
      POSTGRES_PASSWORD: "postgres"

volumes:
  vscode-server:
  vscode-server-insiders:
