name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure environment
        run: cp example.env compose/adit_dev/.env

      - name: Start containers
        run: docker-compose -p adit_ci -f "compose/adit_dev/docker-compose.dev.yml" up -d --build

      - name: Run linting with prospector
        run: docker-compose -p adit_ci -f "compose/adit_dev/docker-compose.dev.yml" exec -T web python -m prospector

      - name: Run tests with pytest
        run: docker-compose -p adit_ci -f "compose/adit_dev/docker-compose.dev.yml" exec -T web python -m pytest --cov=adit

      - name: Stop containers
        if: ${{ always() }}
        run: docker-compose -p adit_ci -f "compose/adit_dev/docker-compose.dev.yml" down --remove-orphans
