name: CI
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and cache Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          target: development
          load: true
          tags: adit_dev:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Configure environment
        run: cp example.env compose/.env.dev

      - name: Start Docker containers
        run: invoke compose-up --no-build

      - name: Run linting with ruff
        # https://github.com/actions/runner/issues/241#issuecomment-745902718
        shell: 'script -q -e -c "bash {0}"'
        run: invoke adit-dev-lint

      - name: Run tests with pytest (and coverage)
        shell: 'script -q -e -c "bash {0}"'
        run: invoke adit-dev-test --cov

      - name: Stop Docker containers
        if: ${{ always() }}
        run: invoke compose-down
