name: CI
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.4.2"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and cache Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          target: development
          load: true
          tags: adit_dev:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Configure environment
        run: cp example.env compose/.env.dev
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dev dependencies
        run: poetry install --with dev
      - name: Start Docker containers
        run: poetry run invoke compose-up --no-build
      - name: Run linting with ruff
        # https://github.com/actions/runner/issues/241#issuecomment-745902718
        shell: 'script -q -e -c "bash {0}"'
        run: poetry run invoke lint
      - name: Run tests with pytest (and coverage)
        shell: 'script -q -e -c "bash {0}"'
        run: poetry run invoke test --cov
      - name: Stop Docker containers
        if: ${{ always() }}
        run: poetry run invoke compose-down
